commit_message: "Update %language% localization from Crowdin"
pull_request_title: "Update localizations from Crowdin"
pull_request_labels: ["l10n"]
append_commit_message: false
files:
  - source: /yuki-iptv.pot
    translation: /po/yuki-iptv-%locale_with_underscore%.po
    export_only_approved: true
    skip_untranslated_files: true
